### ISSUE TITLE
Open Forest R6 Kick-off Workshop

### ISSUE THREAD

**Issue by lisamcmichael** [18F/fs-open-forest-middlelayer-api#184]
I'll be adding images of the forests' "life of a permit" workflow mapping exercise. Also, I'll add images of what took place too.

Next - talk to Eric about how to document requirements captured during the workshop.

**Comment by lisamcmichael** [comment]
[https://app.zenhub.com/files/81612600/b7442e14-0eb6-4f92-a2ac-462b0bbdb9bd/download]

**Comment by lisamcmichael** [comment]
@carlsonem - you should have a v1 of the Open Forest R6 kickoff notes I emailed today.

**Comment by carlsonem** [comment]
OBE by 109
